---
- name: Ensure user for production has access to the database
  become: true
  become_user: postgres
  postgresql_user: 
    name: "{{ item }}"
    login_user: postgres
    password: "{{ item }}"
    state: present
  with_items:
    - confluence-prd
    - jira-prd
    - crown-prd

- name: Ensure databases for production are created
  become: true
  become_user: postgres
  postgresql_db: 
    name: "{{ item }}"
    owner: "{{ item }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    state: present
  with_items:
    - confluence-prd
    - jira-prd
    - crown-prd

- name: Ensure user does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user: 
    name: "{{ item }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  with_items: 
    - confluence-prd
    - jira-prd
    - crown-prd